"""
Streamlit Cloud integration for AI Orchestrator.
Prepares and manages Streamlit app deployments via GitHub.

Note: Streamlit Community Cloud doesn't have a public API.
This integration helps prepare repos for deployment and tracks status.
"""

import os
import json
from datetime import datetime
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field
from pathlib import Path

from ..config import DEPLOY_REGISTRY_PATH


@dataclass
class StreamlitAppConfig:
    """Configuration for a Streamlit app."""

    name: str
    github_repo: str
    main_file: str = "app.py"
    branch: str = "main"
    python_version: str = "3.10"
    requirements: List[str] = field(default_factory=list)
    secrets: Dict[str, str] = field(default_factory=dict)


@dataclass
class StreamlitDeployment:
    """Information about a Streamlit deployment."""

    id: str
    name: str
    github_repo: str
    branch: str
    main_file: str
    url: Optional[str]
    status: str  # preparing, deployed, failed
    created_at: str
    updated_at: str
    error: Optional[str] = None


class StreamlitCloudClient:
    """
    Client for Streamlit Cloud deployments.

    Features:
    - Prepare repositories for Streamlit deployment
    - Generate requirements.txt and configuration
    - Track deployment status
    - Manage app secrets
    """

    # Standard Streamlit app template
    APP_TEMPLATE = '''"""
{description}

Generated by AI Orchestrator.
"""

import streamlit as st

st.set_page_config(
    page_title="{title}",
    page_icon="🚀",
    layout="wide",
)

st.title("{title}")

st.markdown("""
{description}
""")

# Your app code here
'''

    # Standard requirements for Streamlit apps
    BASE_REQUIREMENTS = [
        "streamlit>=1.30.0",
    ]

    def __init__(self, github_token: Optional[str] = None):
        """
        Initialize Streamlit Cloud client.

        Args:
            github_token: GitHub token for repo operations
        """
        self.github_token = github_token or os.environ.get("GITHUB_TOKEN")
        self._deployments: Dict[str, StreamlitDeployment] = {}
        self._load_deployments()

    def _load_deployments(self) -> None:
        """Load deployments from registry file."""
        registry_path = Path(DEPLOY_REGISTRY_PATH)
        if registry_path.exists():
            try:
                data = json.loads(registry_path.read_text())
                streamlit_data = data.get("streamlit", {})
                for dep_id, dep_data in streamlit_data.items():
                    self._deployments[dep_id] = StreamlitDeployment(**dep_data)
            except Exception:
                pass

    def _save_deployments(self) -> None:
        """Save deployments to registry file."""
        registry_path = Path(DEPLOY_REGISTRY_PATH)
        registry_path.parent.mkdir(parents=True, exist_ok=True)

        # Load existing registry or create new
        if registry_path.exists():
            try:
                data = json.loads(registry_path.read_text())
            except Exception:
                data = {}
        else:
            data = {}

        # Update streamlit section
        data["streamlit"] = {
            dep_id: {
                "id": dep.id,
                "name": dep.name,
                "github_repo": dep.github_repo,
                "branch": dep.branch,
                "main_file": dep.main_file,
                "url": dep.url,
                "status": dep.status,
                "created_at": dep.created_at,
                "updated_at": dep.updated_at,
                "error": dep.error,
            }
            for dep_id, dep in self._deployments.items()
        }

        registry_path.write_text(json.dumps(data, indent=2))

    # =========================================================================
    # Deployment Preparation
    # =========================================================================

    def prepare_deployment(
        self,
        config: StreamlitAppConfig,
    ) -> Dict[str, str]:
        """
        Prepare files for Streamlit Cloud deployment.

        Args:
            config: App configuration

        Returns:
            Dict of {filename: content} to be pushed to GitHub
        """
        files = {}

        # Generate requirements.txt
        all_requirements = self.BASE_REQUIREMENTS + config.requirements
        files["requirements.txt"] = "\n".join(sorted(set(all_requirements)))

        # Generate .streamlit/config.toml
        config_toml = """[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
"""
        files[".streamlit/config.toml"] = config_toml

        # Generate .streamlit/secrets.toml template (not actual secrets)
        if config.secrets:
            secrets_template = "# Secrets template - configure in Streamlit Cloud dashboard\n"
            for key in config.secrets:
                secrets_template += f'# {key} = "your-value-here"\n'
            files[".streamlit/secrets.toml.template"] = secrets_template

        # Generate runtime.txt for Python version
        files["runtime.txt"] = f"python-{config.python_version}"

        return files

    def generate_app_skeleton(
        self,
        name: str,
        description: str = "",
    ) -> str:
        """
        Generate a basic Streamlit app skeleton.

        Args:
            name: App name/title
            description: App description

        Returns:
            Python code for app.py
        """
        return self.APP_TEMPLATE.format(
            title=name,
            description=description or f"{name} - A Streamlit app",
        )

    # =========================================================================
    # Deployment Management
    # =========================================================================

    def register_deployment(
        self,
        name: str,
        github_repo: str,
        branch: str = "main",
        main_file: str = "app.py",
    ) -> StreamlitDeployment:
        """
        Register a new Streamlit deployment.

        Args:
            name: App name
            github_repo: GitHub repository (owner/repo)
            branch: Branch to deploy
            main_file: Main Python file

        Returns:
            Deployment info
        """
        import hashlib

        dep_id = hashlib.sha256(
            f"{github_repo}-{branch}-{main_file}".encode()
        ).hexdigest()[:12]

        now = datetime.utcnow().isoformat()

        # Generate expected URL
        # Format: https://[app-name]-[username].streamlit.app
        repo_parts = github_repo.split("/")
        if len(repo_parts) == 2:
            username = repo_parts[0].lower().replace("_", "-")
            app_slug = name.lower().replace(" ", "-").replace("_", "-")
            expected_url = f"https://{app_slug}-{username}.streamlit.app"
        else:
            expected_url = None

        deployment = StreamlitDeployment(
            id=dep_id,
            name=name,
            github_repo=github_repo,
            branch=branch,
            main_file=main_file,
            url=expected_url,
            status="preparing",
            created_at=now,
            updated_at=now,
        )

        self._deployments[dep_id] = deployment
        self._save_deployments()

        return deployment

    def update_deployment_status(
        self,
        deployment_id: str,
        status: str,
        url: Optional[str] = None,
        error: Optional[str] = None,
    ) -> Optional[StreamlitDeployment]:
        """
        Update deployment status.

        Args:
            deployment_id: Deployment ID
            status: New status
            url: Actual URL (once deployed)
            error: Error message if failed

        Returns:
            Updated deployment or None if not found
        """
        if deployment_id not in self._deployments:
            return None

        deployment = self._deployments[deployment_id]
        deployment.status = status
        deployment.updated_at = datetime.utcnow().isoformat()

        if url:
            deployment.url = url
        if error:
            deployment.error = error

        self._save_deployments()
        return deployment

    def get_deployment(self, deployment_id: str) -> Optional[StreamlitDeployment]:
        """Get deployment by ID."""
        return self._deployments.get(deployment_id)

    def list_deployments(
        self,
        status: Optional[str] = None,
    ) -> List[StreamlitDeployment]:
        """
        List all Streamlit deployments.

        Args:
            status: Filter by status (optional)

        Returns:
            List of deployments
        """
        deployments = list(self._deployments.values())

        if status:
            deployments = [d for d in deployments if d.status == status]

        return sorted(deployments, key=lambda d: d.updated_at, reverse=True)

    def delete_deployment(self, deployment_id: str) -> bool:
        """
        Remove deployment from registry.

        Args:
            deployment_id: Deployment ID

        Returns:
            True if deleted
        """
        if deployment_id in self._deployments:
            del self._deployments[deployment_id]
            self._save_deployments()
            return True
        return False

    # =========================================================================
    # Helper Methods
    # =========================================================================

    def get_deployment_instructions(self, github_repo: str) -> str:
        """
        Get instructions for deploying to Streamlit Cloud.

        Args:
            github_repo: GitHub repository

        Returns:
            Markdown instructions
        """
        return f"""## Deploy to Streamlit Cloud

1. Go to [share.streamlit.io](https://share.streamlit.io)
2. Click "New app"
3. Select repository: `{github_repo}`
4. Set Main file path: `app.py`
5. Click "Deploy"

### Configure Secrets (if needed)

After deployment:
1. Go to your app's settings
2. Click "Secrets"
3. Add your secrets in TOML format:

```toml
API_KEY = "your-api-key"
DATABASE_URL = "your-database-url"
```

### Monitor Your App

- View logs in the Streamlit Cloud dashboard
- Check app health at your app URL
"""


# Singleton instance
_streamlit_client: Optional[StreamlitCloudClient] = None


def get_streamlit_cloud_client() -> StreamlitCloudClient:
    """Get or create StreamlitCloudClient singleton."""
    global _streamlit_client
    if _streamlit_client is None:
        _streamlit_client = StreamlitCloudClient()
    return _streamlit_client


def reset_streamlit_cloud_client() -> None:
    """Reset the singleton."""
    global _streamlit_client
    _streamlit_client = None
